on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'https://gitpub.ahost.win/ahost/shellbale.git'
          source_branch: 'main'
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sync_tags: "true"
